INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (1,'EMB-145LR','RAF St Athan',182);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (2,'EMB-145XR','Sky Harbor Air Service',91);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (3,'EMB-145XR','Tadair',146);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (4,'EMB-145XR','Viking Airlines',55);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (5,'EMB-145XR','Pyramid Air Lines',138);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (6,'EMB-145LR','Starspeed',125);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (7,'EMB-145XR','SENEAM',72);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (8,'EMB-145XR','Sonair Servico Aereo',90);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (9,'EMB-145XR','Samson Aviation',51);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (10,'A320-214','Rusline',77);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (11,'EMB-145XR','Flugfelag Vestmannaeyja',148);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (12,'EMB-145XR','Austrian Airlines',180);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (13,'EMB-145XR','Boliviana de Aviacion',192);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (14,'A320-214','Hellenic Star Airways',87);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (15,'A320-214','SASCO Airlines',171);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (16,'A320-214','XP Internation',70);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (17,'A320-214','Western Air',77);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (18,'EMB-145XR','Rutland Aviation',82);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (19,'A320-214','Universal Airlines',186);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (20,'EMB-145XR','Turkish Airlines',180);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (21,'EMB-145XR','Executive AirShare',151);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (22,'A320-214','Twin Town Leasing Company',181);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (23,'A320-214','Sheremetyevo-Cargo',61);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (24,'EMB-145XR','Zapolyarie Airlines',75);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (25,'A320-214','Swedeways',97);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (26,'EMB-145XR','Tramon Air',180);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (27,'EMB-145XR','Raven Air',154);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (28,'A320-214','Grand China Air',163);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (29,'EMB-145XR','Zantop International Airlines',127);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (30,'A320-214','South West Air',157);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (31,'EMB-145XR','Universal Airways',197);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (32,'EMB-145XR','Xclusive Jet Charter Limited',64);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (33,'A320-214','Seacoast Airlines',129);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (34,'EMB-145XR','Victor Tagle Larrain',162);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (35,'EMB-145XR','Trans Continental Airlines',184);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (36,'EMB-145XR','US Army Parachute Team',193);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (37,'A320-214','Super Luza',102);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (38,'EMB-145XR','Trans Asian Airlines',117);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (39,'EMB-145XR','RAF Leuchars',186);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (40,'EMB-145XR','Bingo Airways',117);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (41,'EMB-145XR','Tobago Express',72);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (42,'EMB-145XR','Stephenville Aviation Services',168);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (43,'A320-214','VIM-Aviaservice',188);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (44,'EMB-145LR','Tango Bravo',76);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (45,'EMB-145XR','WRA Inc',129);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (46,'EMB-145XR','Turkish Airlines',197);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (47,'EMB-145XR','Jupiter Airlines',102);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (48,'EMB-145XR','Air Engiadina-BRN',162);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (49,'EMB-145XR','Stichting Vliegschool 16Hoven',142);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (50,'A320-214','Royal Daisy Airlines',162);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (51,'EMB-145XR','Wings Airways',126);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (52,'EMB-145XR','Transportes Aereos Cielos Andinos',121);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (53,'EMB-145XR','Kan Air',110);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (54,'A320-214','River Ministries Air Charter',154);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (55,'EMB-145XR','Seacoast Airlines',163);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (56,'A320-214','Servicios Aereos Nacionales',173);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (57,'EMB-145XR','Xerox Corporation',156);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (58,'A320-214','Taquan Air Services',100);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (59,'A320-214','Southern Cross Aviation',84);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (60,'EMB-145XR','Qatar Air Cargo',66);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (61,'EMB-145XR','Trabajos Aereos Murcianos',86);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (62,'EMB-145XR','Servicios Aeronauticos Aero Personal',111);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (63,'EMB-145LR','Compania de Aviacion Faucett',79);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (64,'EMB-145LR','Servicios Aereos Ejecutivos De La Laguna',140);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (65,'EMB-145XR','Streamline',56);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (66,'EMB-145XR','Quebec Government Air Service',80);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (67,'A320-214','Wings of Lebanon Aviation',194);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (68,'EMB-145XR','Boliviana de Aviacion',99);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (69,'EMB-145XR','TG Aviation',160);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (70,'EMB-145XR','Sedona Air Center',149);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (71,'A320-214','Tbilisi Aviation University',101);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (72,'A320-214','Swift Air (Interstate Equipment Leasing)',105);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (73,'EMB-145XR','Raya Jet',156);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (74,'A320-214','The Army Aviation Heritage Foundation',76);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (75,'A320-214','Sirvair',96);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (76,'EMB-145XR','Sundorph Aeronautical Corporation',68);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (77,'A320-214','Wings Aviation',61);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (78,'EMB-145XR','Transport Africa',195);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (79,'EMB-145XR','Slate Falls Airways',117);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (80,'EMB-145XR','Vega Aviation',66);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (81,'EMB-145XR','XP Internation',115);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (82,'A320-214','Wings of Lebanon Aviation',141);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (83,'A320-214','VIP Air',143);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (84,'EMB-145XR','United Kingdom Royal VIP Flight',115);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (85,'EMB-145XR','TAG Aviation USA',123);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (86,'A320-214','Texas Airlines',159);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (87,'EMB-145XR','Air Engiadina-BRN',134);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (88,'EMB-145XR','Spectrum Air Service',79);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (89,'EMB-145XR','Shalom Air Services',196);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (90,'A320-214','Vichi',176);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (91,'A320-214','Vichi',94);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (92,'A320-214','Sun Freight Logistics',91);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (93,'EMB-145XR','Trans American Airlines (Trans Am)',57);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (94,'A320-214','Saber Airlines',69);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (95,'EMB-145XR','Universal Airlines',136);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (96,'EMB-145XR','Simrik Airlines',57);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (97,'A320-214','Zhejiang Airlines',178);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (98,'A320-214','Spanish Air Force',51);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (99,'A320-214','Top Sky International',153);
INSERT INTO Plane(plane_id,model,airline,capacity) VALUES (100,'EMB-145XR','Taxi Aereo Turistico',134);
